### PR TITLE
News

### PR DESCRIPTION
**Pull request by nsg**
a blog post = a news post, using the folder `news/`.

This is still a work in progress but what I have is:

* A index.tmpl that renders the latest post in a jumbotron.
* Use the category system to place posts in categories by year
* Browse categories by year, like `/aktuellt/year/2017/`

So by the look of it, we can probably just use the blog system for news. I will finish this tomorrow.

### CODE REVIEW

**Comment by nsg** [comment]
Moved things around and rebased on top of master.

I think I will stick to English urls, so /news/ in favor of /aktuellt/. I also removed the year part of the url so we now have things like:

normal pages: `/` `/foo/` `/foo/bar/`
news by year (categories): `/news/`
news for 2017: `/news/2017/`
a news post in 2017: `/news/2017/stuff`
We also have a news index at `/news/index`... not sure if it's useful.

**Comment by nsg** [comment]
Enabled tags under `/news/tags/tagname`, for example we do now have two dummy news:

    stacken/news/
    ├── 2016
    │   └── test2.md
    └── 2017
        └── test.md

```
$ cat stacken/news/2016/test2.md 
<!--
.. title: A test
.. slug: test2
.. date: 2016-08-18 00:00:00 CEST
.. tags: blaha
.. category: 2016
.. description:
.. author: nsg
-->

test, test
```

```
$ cat stacken/news/2017/test.md 
<!--
.. title: Ny hemsida 2017
.. slug: test
.. date: 2017-08-18 00:00:00 CEST
.. tags: blaha
.. description:
.. category: 2017
.. author: nsg
-->

test, test
```

The `category` metadata is used for yearly archives so they are listed under `/news/2017` and 2016. but both are tagged `blaha` so we find both under `/news/tags/blaha/`.

**Comment by nsg** [comment]
The menu now points to the news index page at `/news/index/`that shows the news. The latest news is shown in a jumbotron. I also updated the latest news with a little more text displaying that you can specify multiple tags and how to use the teaser feature.

**Comment by nsg** [comment]
I'm quite happy with this now ... I think it's time to populate the site with content and see how it looks.

I will ping you @medik for information, and check out what I have written here above, there are a few examples there.

**Comment by medik** [comment]
It looks great, however, I have a few questions in regards to the `/news/index` page. I think that the categories should be in a separate catalogue i.e. `/news/year/` (if we decide to categorize it in years) or `/news/categories/`. As it looks now, the Nikola build engine creates a taxonomy tree in `/news/`. Was this intended? How is `/news/year/2017/testpage/` less sane than `/news/2017/testpage/`?

**Comment by nsg** [comment]
I liked to keep a logical URL pattern with `/news/<year>/<post>/`, to navigate up to a less specific segment (year) you can strip the last segment of the url to `/news/<year>/` and `/news/` for all the news.

Regarding `/news/year/<year>/`, the year part felt redundant if we only use it for years, and if you choose to use this pattern posts has to be posted under `news/year/2017/foo.md` as well to keep the same url pattern. I did not like that, so that's the reason.

`/news/index/` is a little weird, but I could not place it under `/news/`because it conflicted with the taxonomy... so it's not perfect but this was my best suggestion.

I'm open to suggestions, @kaj you do webstuff ... what do you think?

post: `/news/<year>/<post>/`
posts of a year: `/news/<year>/`
all years: `/news/`
latest news: `/news/index/` (possible rename `index`)

vs. 

post: `/news/year/<year>/<post>/`
posts of a year: `/news/year/<year>/`
all years: `/news/year/`
latest news: `/news/`

**Pull request merged**
