### PR TITLE
Mark current page as active in menu

### PR DESCRIPTION
**Pull request by Frost**

### CODE REVIEW

**Comment by Frost** [comment]
2017-08-20-211048_744x108_scrot

**Comment by nsg** [comment]
works: http://localhost:8000/club/
do not works: http://localhost:8000/club/officers/

**Comment by Frost** [comment]
I wasn't aware that there were pages that aren't accessible from the menu. I understand why you think it looks weird when it doesn't work on some pages, but for the officers page, which menu link do you think should be highlighted?

**Comment by nsg** [comment]
It's a subpage under club, so... club.

**Comment by kaj** [comment]
While I kind-of agree with @nsg , I think that could just as easily be added later.  So, if subpage matching can be easily fixed, please do, but if it is more complicated then this is better than nothing, so please merge.

**Pull request merged**
